// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

// #include "ui_Screen1.h"
// #include "ui_Screen2.h"
#include "ui_Screen3.h"
// #include "ui_Screen4.h"

///////////////////// VARIABLES ////////////////////


// EVENTS
// extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui____initial_actions0;
// extern lv_chart_series_t * ui_Chart2_series_1;
// extern lv_chart_series_t * ui_Chart2_series_2;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_wifi2_png);    // assets/wifi.png





// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
